/:
    template: slides.twig
    variables:
        slides: src/slides/

/slides/{id}:
    template: slide.twig
    variables:
        slide: src/slides/
    config:
        collection:
            variable: slide
            parameter: id
